name: CI for .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        dotnet-version: [5.0.x]
        os: [ubuntu-latest]        
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x   

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        my-resume-connection: ${{ secrets.MY_RESUME_CONNECTION }}
  docker:
    runs-on: ubuntu-latest
    # Wait for test cases to complete before building and pushing the container image
    needs: build 
    steps:
    - uses: actions/checkout@v2

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ranjeethmd/my-resume:v6
